nelmio_api_doc:
    documentation:
        info:
            title: BileMo API
            description: vente de smartphones hauts de gamme en B2B
            version: 1.0.0
        paths:
            /api/login:
                post:
                    #summary: use this route to log
                    consumes:
                        - application/json
                    parameters:
                        - in: body
                          name: customer
                          description: veuillez remplir les données de client
                          schema:
                              type: object
                              required:
                                  - login
                              properties:
                                  login:
                                      type: string
                                  password:
                                      type: string
            /api/users:
                post:
                    #summary: create a user (customers only)
                    parameters:
                        - in: body
                          name: user
                          schema:
                              type: object
                              required:
                                  - login
                              properties:
                                  firstname:
                                      type: string
                                  lastname:
                                      type: string
                                  mail:
                                      type: string
                                  password:
                                      type: string
            #/api/users:
                #get:
                    #summary: customer's users list (customers only)
            /api/users/{id}:
                put:
                    #summary: edit a user (customers only)
                    parameters:
                        - in: body
                          name: user
                          schema:
                              type: object
                              required:
                                  - login
                              properties:
                                  login:
                                      type: string
                                  password:
                                      type: string
            /api/customers:
                post:
                    #summary: post new customer (admin only)
                    parameters:
                        - in: body
                          name: customers
                          schema:
                              type: object
                              required:
                                  - login
                              properties:
                                  login:
                                      type: string
                                  password:
                                      type: string
                                  society:
                                      type: string
            /api/customers/{id}:
                put:
                    #summary: edit a customer (admin only)
                    parameters:
                        - in: body
                          name: customers
                          schema:
                              type: object
                              required:
                                  - login
                              properties:
                                  login:
                                      type: string
                                  password:
                                      type: string
                                  society:
                                      type: string
            /api/phones:
                post:
                    #summary: post new phone (admin only)
                    parameters:
                        - in: body
                          name: user
                          schema:
                              type: object
                              required:
                                  - login
                              properties:
                                  price:
                                      type: double
                                  DAS:
                                      type: double
                                  model:
                                      type: string
                                  releaseDate:
                                      type: DateTime
                                  screenSize:
                                      type: double
                                  connexionType:
                                      type: string
                                  width:
                                      type: double
                                  height:
                                      type: double
                                  thickness:
                                      type: double
                                  weight:
                                      type: double
                                  pixelsX:
                                      type: integer
                                  pixelsY:
                                      type: integer
                                  cameraSpecifications:
                                      type: string
                                  battery:
                                      type: double
                                  comments:
                                      type: string
            /api/phones/{id}:
                put:
                    #summary: edit a phone (admin only)
                    parameters:
                        - in: body
                          name: user
                          schema:
                              type: object
                              required:
                                  - login
                              properties:
                                  price:
                                      type: double
                                  DAS:
                                      type: double
                                  model:
                                      type: string
                                  releaseDate:
                                      type: DateTime
                                  screenSize:
                                      type: double
                                  connexionType:
                                      type: string
                                  width:
                                      type: double
                                  height:
                                      type: double
                                  thickness:
                                      type: double
                                  weight:
                                      type: double
                                  pixelsX:
                                      type: integer
                                  pixelsY:
                                      type: integer
                                  cameraSpecifications:
                                      type: string
                                  battery:
                                      type: double
                                  comments:
                                      type: string
    areas: # to filter documented areas
        path_patterns:
            - ^/api(?!/doc$) # Accepts routes under /api except /api/doc
